services:
    _defaults:
        public: true

    Instride\Bundle\OpenDxpElementManagerBundle\Command\IndexCommand:
        arguments:
          - '@Instride\Bundle\OpenDxpElementManagerBundle\Metadata\DuplicatesIndex\MetadataRegistry'
          - '@Instride\Bundle\OpenDxpElementManagerBundle\DuplicateIndex\DuplicatesIndexWorker'
          - '@Instride\Bundle\OpenDxpElementManagerBundle\DuplicateIndex\DuplicateFinder'
          - '@event_dispatcher'
        tags:
          - { name: console.command, command: 'opendxp-element-manager:duplicate-index' }
