opendxp_element_manager_admin_duplicate_index_list:
    path: /admin/opendxp-element-manager/potential-duplicate/list
    methods: [GET]
    defaults:
        _controller: Instride\Bundle\OpenDxpElementManagerBundle\Controller\Admin\DuplicatesIndexController::listAction

opendxp_element_manager_admin_duplicate_index_get:
    path: /admin/opendxp-element-manager/potential-duplicate/get
    methods: [GET]
    defaults:
        _controller: Instride\Bundle\OpenDxpElementManagerBundle\Controller\Admin\DuplicatesIndexController::getAction

opendxp_element_manager_admin_duplicate_index_get_potential_duplicates:
    path: /admin/opendxp-element-manager/potential-duplicate/get-potential-duplicates
    methods: [GET]
    defaults:
        _controller: Instride\Bundle\OpenDxpElementManagerBundle\Controller\Admin\DuplicatesIndexController::getPotentialDuplicatesAction

opendxp_element_manager_admin_duplicate_index_decline:
    path: /admin/opendxp-element-manager/potential-duplicate/decline
    methods: [POST]
    defaults:
        _controller: Instride\Bundle\OpenDxpElementManagerBundle\Controller\Admin\DuplicatesIndexController::declineDuplicationAction

opendxp_element_manager_admin_duplicate_index_undecline:
    path: /admin/opendxp-element-manager/potential-duplicate/undecline
    methods: [POST]
    defaults:
        _controller: Instride\Bundle\OpenDxpElementManagerBundle\Controller\Admin\DuplicatesIndexController::unDeclineDuplicationAction
